version: '3.4'

volumes:
  postgresql-db:
    driver: local
  certs:
    external: true

services:
  db:
    restart: always
    image: postgres:15.1
    container_name: pleroma-db
    environment:
      POSTGRES_USER: pleroma
      POSTGRES_PASSWORD: ${PLEROMA_DB_PASSWORD}
      POSTGRES_DB: pleroma
    volumes:
      - ${PLEROMA_DB_DIR}:/var/lib/postgresql/data
      - ./postgres:/docker-entrypoint-initdb.d
      - ./pgdunp:/pgdunp
    ports:
      - "5432:5432"
    networks:
      - back-pleroma

  web:
    build: docker/otp/.
    image: pleroma
    #container_name: pleroma_web
    restart: always
    environment:
      MIX_ENV: prod
    ports:
      - '4000:4000'
    volumes:
      - ./data/pleroma/content/uploads:/var/lib/pleroma/uploads
      - ./pleroma-custom/static:/var/lib/pleroma/static
      - ./data/pleroma/config:/etc/pleroma:ro
    depends_on:
      - db
    networks:
      - caddy
      - back-pleroma
    labels:
      caddy: ${PLEROMA_HOSTNAME}
      caddy.reverse_proxy: "web:4000"

networks:
  caddy:
    external: true
  back-pleroma:
    external: true
